[workspace]
members = [
    "picoprog",
    "serprog"
]
resolver = "2"

[workspace.dependencies]
assign-resources = "0.4.1"
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embassy-executor = "0.7.0"
embassy-futures = "0.1.1"
embassy-rp = "0.3.0"
embassy-sync = "0.6.2"
embassy-time = "0.4.0"
embassy-usb = "0.4.0"
embassy-usb-logger = "0.4.0"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
futures = { version = "0.3.31", default-features = false }
heapless = "0.8.0"
log = "0.4.26"
num_enum = { version = "0.7.3", default-features = false }
portable-atomic = "1.11.0"
serprog = { path = "./serprog" }
static_cell = "2.1.0"
tock-registers = "0.9.0"
ufmt = "0.2.0"
zerocopy = "0.8.21"

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }
embassy-usb-logger = { git = "https://github.com/embassy-rs/embassy", rev = "17301c00e986c5b8536435ea31ebf5aaf13aed17" }

[profile.release]
debug = true
incremental = false
codegen-units = 1
opt-level = "s"
lto = "fat"
