[target.thumbv8m.main-none-eabihf]
linker = "flip-link"
#runner = 'probe-rs run --chip STM32U5A5ZJTxQ'
runner = "/home/arthur/src/probe-rs/target/release/probe-rs run --host ws://calculator.lab.9e.network:3000 --token flater1c --protocol swd --chip STM32U5A5ZJTxQ"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
