M48
; DRILL file {KiCad 8.0.4} date 2024-08-16T15:14:09+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-16T15:14:09+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.4736Y-4.7274
X5.4736Y-4.9183
T2
X5.3543Y-4.7156
X5.3543Y-4.9301
M30
