[package]
name = "picoprog"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Marvin Drees <marvin.drees@9elements.com>"]

[dependencies]
assign-resources.workspace = true
cortex-m = { workspace = true, features = ["critical-section", "inline-asm"] }
cortex-m-rt.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
embassy-executor = { workspace = true, features = ["arch-cortex-m", "defmt", "executor-interrupt", "executor-thread", "nightly"] }
embassy-futures.workspace = true
embassy-rp = { workspace = true, features = ["critical-section-impl", "defmt", "rom-func-cache", "rom-v2-intrinsics", "rp2040", "time-driver", "unstable-pac"] }
embassy-sync = { workspace = true, features = ["defmt"] }
embassy-time = { workspace = true, features = ["defmt", "defmt-timestamp-uptime"] }
embassy-usb = { workspace = true, features = ["defmt"] }
embedded-hal = { workspace = true, features = ["defmt-03"] }
embedded-hal-async = { workspace = true, features = ["defmt-03"] }
futures = { workspace = true, default-features = false, features = ["async-await", "cfg-target-has-atomic", "unstable"] }
heapless = { workspace = true, features = ["portable-atomic-critical-section", "ufmt"] }
panic-probe = { workspace = true, features = ["print-defmt"] }
portable-atomic = { workspace = true, features = ["critical-section"] }
serprog.workspace = true
static_cell.workspace = true
ufmt.workspace = true
