[package]
name = "picoprog"
version = "0.1.0"
authors = ["Marvin Drees <marvin.drees@9elements.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
assign-resources.workspace = true
cortex-m = { workspace = true, features = ["critical-section", "inline-asm"] }
cortex-m-rt.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
embassy-executor = { workspace = true, features = [
  "arch-cortex-m",
  "defmt",
  "executor-interrupt",
  "executor-thread",
  "nightly",
] }
embassy-futures.workspace = true
embassy-rp = { workspace = true, features = [
  "critical-section-impl",
  "rom-func-cache",
  "rom-v2-intrinsics",
  "rp2040",
  "time-driver",
  "unstable-pac",
] }
embassy-sync = { workspace = true, features = ["defmt"] }
embassy-time.workspace = true
embassy-usb = { workspace = true, features = [
  "defmt",
  "max-handler-count-6",
  "max-interface-count-6",
] }
embedded-hal.workspace = true
embedded-hal-async.workspace = true
heapless = { workspace = true, features = [
  "portable-atomic-critical-section",
  "ufmt",
] }
log.workspace = true
serprog.workspace = true
static_cell.workspace = true
ufmt.workspace = true
