[target.'cfg(all(target_arch = "arm", target_os = "none"))']
linker = "flip-link"
runner = "elf2uf2-rs"

[build]
target = "thumbv6m-none-eabi"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
