[package]
name = "serprog"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
embassy-usb.workspace = true
embedded-hal-async.workspace = true
embedded-hal.workspace = true
futures = { workspace = true, default-features = false, features = ["async-await", "unstable"] }
log.workspace = true
num_enum = { workspace = true, default-features = false }
tock-registers.workspace = true
zerocopy = { workspace = true, features = ["derive"] }
