[package]
name = "bluepill-prog"
version = "0.1.0"
authors = ["Arthur Heymans <arthur@aheymans.xyz>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
assign-resources.workspace = true
cortex-m = { workspace = true, features = [
  "critical-section-single-core",
  "inline-asm",
] }
cortex-m-rt.workspace = true
critical-section.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
embassy-executor = { workspace = true, features = [
  "arch-cortex-m",
  "defmt",
  "executor-thread",
  "nightly",
] }
embassy-futures = { workspace = true, features = ["defmt"] }
embassy-stm32 = { workspace = true, features = [
  "defmt",
  "memory-x",
  "rt",
  "stm32f103c8",
  "time-driver-any",
] }
embassy-sync = { workspace = true, features = ["defmt"] }
embassy-time = { workspace = true, features = [
  "defmt",
  "defmt-timestamp-uptime",
  "tick-hz-32_768",
] }
embassy-usb = { workspace = true, features = ["defmt"] }
futures.workspace = true
heapless = { workspace = true, features = [
  "defmt-03",
  "portable-atomic",
  "portable-atomic-critical-section",
  "ufmt",
] }
panic-probe.workspace = true
portable-atomic.workspace = true
serprog.workspace = true
static_cell.workspace = true
stm32-fmc = { workspace = true, features = ["defmt"] }
ufmt.workspace = true
